jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: obfuscator.jar
        path: obfuscator-core/target/obfuscator-core-1.9.3-SNAPSHOT.jar
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
